language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.gemfile
matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/activerecord_5.gemfile
