language: ruby
rvm:
  - 2.1.7
  - 2.2.3
gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_5.gemfile
matrix:
  exclude:
    - rvm: 2.1.7
      gemfile: gemfiles/activerecord_5.gemfile
